### ISSUE TITLE
msmtprc is always overwritten on first run

### ISSUE THREAD

**Issue by Lukas0907** [adferrand/docker-backuppc#37]
Hi,

first of all, thank you for sharing this Docker setup. It works very well!

While you mention that one should bind mount/copy the file ".msmtprc" to /home/backuppc, I would like to use the file /etc/msmtprc instead. For that it would be handy if the file /etc/msmtprc was not overwritten if it already exists (see https://github.com/adferrand/docker-backuppc/blob/master/files/entrypoint.sh#L107). Then it would be possible to simply bind mount the file from the host into the same location in the container.

Regards,
Lukas

**Comment by pgassmann** [comment]
I was also debugging sending mails. There is now an update to configure an option to configure SendMailArgs, which is especially used configure msmtprc 

https://github.com/backuppc/backuppc/pull/385

**Comment by pgassmann** [comment]
The issue is homemade. Even though the readme states, that one can mount msmtprc it does no longer work due to the entrypoint script overwriting it.

**Comment by adferrand** [comment]
Thanks guys for the update. I will look at it as soon as possible.

**Comment by adferrand** [comment]
Ok, I will add a control in the entrypoint to avoid to overwrite `/etc/msmtprc` if it already exists.

@pgassmann, using `/home/backuppc/.msmtprc` is something that works out-of-the-box however. As a lot of Unix tools, `msmtprc` will try first to use the configuration file in the user's folder, then fallback to the system wide one.

**Comment by pgassmann** [comment]
> @pgassmann, using `/home/backuppc/.msmtprc` is something that works out-of-the-box however. As a lot of Unix tools, `msmtprc` will try first to use the configuration file in the user's folder, then fallback to the system wide one.

When BackupPC sends mails, it does **not use** the .msmtprc in the home folder. Probably because the user is not switched fully.

* When inside the container switching to backuppc with `su - backuppc` then `/home/backuppc/.msmtprc`is used. 
* when switching the user using `su -m backuppc` sendmail uses only `/etc/msmtprc`

`su -m backuppc` is what's suggested when trying to execute BackupPC_SendEmail as Root.

@adferrand The Documentation in the [README#advanced-smtp-configuration](https://github.com/adferrand/docker-backuppc#advanced-smtp-configuration) is not true (anymore?).

**Comment by pgassmann** [comment]
@adferrand I see that you already have implemented a fix. Can you make a new release of the image?

**Comment by adferrand** [comment]
Here you are!

**Comment by avkhozov** [comment]
Hi @adferrand, I see that the latest version is 4.4.0-2 on hub.docker.com. Could you please upload a version 4.4.0-4?

**Comment by adferrand** [comment]
Ok I fixed the deployment pipeline. New docker images are pushed again on Docker Hub.
